---
# ====== Application: PokéAPEX ===============================
id: 100
identification: 
  name: PokéAPEX
  alias: POKEAPEX
  version: Release 1.0

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Public # 42055800808689869628

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Allow
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: #CUSTOM_SCHEMA

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '#APP_FILES#icons/charizard_pixel.png'
  text: PokéAPEX

progressive-web-app: 
  enable: true
  installable: true
  display: Fullscreen
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:11:&SESSION.'
    page: 11 # Pokémon

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu # 7073982926170526156
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--default
  - t-TreeNav--classic
  list-position: Side
  list: Navigation Menu # 7073618264066526071

navigation-bar: 
  implementation: List
  list: Navigation Bar # 7074112103905526289
  list-template: Navigation Bar # 7073982517791526155
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#APP_FILES#js/clarity.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_FILES#css/main#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: pokeapex

component-settings: 
- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 7073614134110526068
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15494100046095

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 7073614465584526068
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15494100046101

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 7073614750973526069
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15494100046103

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 7073615085550526069
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15494100046109

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 7073615338895526069
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15494100046112

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 7073615720100526069
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15494100046112

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 7073615953102526069
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 15494100046115

- # ====== Component Setting: NATIVE_IR ========================
  id: 7073616242068526069
  identification: 
    name: NATIVE_IR
    type: Region

  settings: 
    attribute-1: IG

  subscription: 
    version-number: 15494100046115

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 7073616542558526069
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 15494100046118

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 7073616869323526070
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15494100046121

